# !/bin/bash -eu
# provision.sh -- Install Apache, a test PHP script and MediaWiki

# Install EPEL
sudo yum install -y http://download.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
#sudo rpm -ivh epel-release-6-8.noarch.rpm

# Install Apache, PHP, mysql, mysql-server, mediawiki119
sudo rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-6
yum install -y httpd php mysql mysql-server gd gd-devel php-gd php-pecl-apc mediawiki119 vsftpd

# Start the services
service httpd start
chkconfig httpd on
sudo service mysqld start
sudo chkconfig mysqld on
sudo service vsftpd start
sudo chkconfig vsftpd on 

# Write a test script
cat > /var/www/html/index.php << EOF
<?php phpinfo(); ?>
EOF

db_root_pw2='thi1313'
db_root_pw=thi1313
#mw_db_usr=wikiuser
#mw_db_pw=dhinn0liz13z
mediawiki_dir=/var/www/html/mediawiki
mediawiki_db=mediawiki
mediawiki_usr=wikiAdmin
mediawiki_pw=fiskeug5redhinn0lizkawf7

sudo /usr/bin/mysqladmin -u root password $db_root_pw2

sudo ln -s /var/www/mediawiki119 $mediawiki_dir 
sudo chown -R apache:apache $mediawiki_dir  
mysql -u root --password=$db_root_pw -e 'create database mediawiki' 
mysql -u root --password=$db_root_pw -e "grant index, create, select, insert, update, delete, alter, lock tables on mediawiki.* to 'wikiuser'@'localhost' identified by 'dhinn0liz13z'";
mysql -u root --password=$db_root_pw -e 'drop database test'
mysql -u root --password=$db_root_pw -e 'delete from mysql.user where user=""'
mysql -u root --password=$db_root_pw -e 'flush privileges'
sudo service httpd restart

cat > /var/www/html/mediawiki/LocalSettings.php << '_EOF_'
<?php
# This file was automatically generated by the MediaWiki 1.19.13
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# http://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename      = "First_Wiki";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs please see:
## http://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath       = "/mediawiki";
$wgScriptExtension  = ".php";

## The protocol and server name to use in fully-qualified URLs
$wgServer           = "http://192.168.56.65";

## The relative URL path to the skins directory
$wgStylePath        = "$wgScriptPath/skins";

## The relative URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogo             = "$wgStylePath/common/images/wiki.png";

## UPO means: this is also a user preference option

$wgEnableEmail      = true;
$wgEnableUserEmail  = true; # UPO

$wgEmergencyContact = "apache@192.168.56.65";
$wgPasswordSender   = "apache@192.168.56.65";

$wgEnotifUserTalk      = false; # UPO
$wgEnotifWatchlist     = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype           = "mysql";
$wgDBserver         = "localhost";
$wgDBname           = "mediawiki";
$wgDBuser           = "wikiuser";
$wgDBpassword       = "dhinn0liz13z";

# MySQL specific settings
$wgDBprefix         = "";

# MySQL table options to use during installation or update
$wgDBTableOptions   = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Experimental charset support for MySQL 5.0.
$wgDBmysql5 = false;

## Shared memory settings
$wgMainCacheType    = CACHE_NONE;
$wgMemCachedServers = array();

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads  = false;
#$wgUseImageMagick = true;
#$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from http://commons.wikimedia.org
$wgUseInstantCommons  = false;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "en_US.utf8";

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
#$wgHashedUploadDirectory = false;

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publically accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/Names.php
$wgLanguageCode = "nl";

$wgSecretKey = "78fad3d8cb842cf731eb55bebce16bd159c4e996b73ce4a4778999bb8cb4e0bf";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "3146153fe13c58d2";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'standard', 'nostalgia', 'cologneblue', 'monobook', 'vector':
$wgDefaultSkin = "vector";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl  = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

# Query string length limit for ResourceLoader. You should only set this if
# your web server has a query string length limit (then set it to that limit),
# or if you have suhosin.get.max_value_length set in php.ini (then set it to
# that value)
$wgResourceLoaderMaxQueryLength = -1;



# End of automatically generated settings.
# Add more configuration options below.

EOF


# cat << _EOF_
# -------------------------------------------------------------------------
 # MEDIAWIKI INSTALLATION ALMOST COMPLETED!
 # Please go to http://192.168.56.65/mediawiki to set up the wiki!!!!!!!!!!!
 # For more info please see the Readme.md file on 
  # https://github.com/SteveBerneel/MediaWiki_SB
# --------------------------------------------------------------------------
# _EOF_









